/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/': RouteRecordInfo<
      '/about/',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/site': RouteRecordInfo<
      '/about/site',
      '/about/site',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives/': RouteRecordInfo<
      '/archives/',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/': RouteRecordInfo<
      '/categories/',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/links/': RouteRecordInfo<
      '/links/',
      '/links',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/page/[page]': RouteRecordInfo<
      '/page/[page]',
      '/page/:page',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/posts/': RouteRecordInfo<
      '/posts/',
      '/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Life-Essays/Am-I-into-light-yuri': RouteRecordInfo<
      '/posts/Life-Essays/Am-I-into-light-yuri',
      '/posts/Life-Essays/Am-I-into-light-yuri',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Life-Essays/I-really-love-RADWIMPS——happy-20th-anniversary!': RouteRecordInfo<
      '/posts/Life-Essays/I-really-love-RADWIMPS——happy-20th-anniversary!',
      '/posts/Life-Essays/I-really-love-RADWIMPS——happy-20th-anniversary!',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Tech-Notes/Git-Failed-to-connect-to-github.com-port-443': RouteRecordInfo<
      '/posts/Tech-Notes/Git-Failed-to-connect-to-github.com-port-443',
      '/posts/Tech-Notes/Git-Failed-to-connect-to-github/com-port-443',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Tech-Notes/Git-Version-Control-Study-Notes': RouteRecordInfo<
      '/posts/Tech-Notes/Git-Version-Control-Study-Notes',
      '/posts/Tech-Notes/Git-Version-Control-Study-Notes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Tech-Notes/githubpages-Quartz-Obsidian-to-bulid-your-Blog': RouteRecordInfo<
      '/posts/Tech-Notes/githubpages-Quartz-Obsidian-to-bulid-your-Blog',
      '/posts/Tech-Notes/githubpages-Quartz-Obsidian-to-bulid-your-Blog',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Tech-Notes/Hello-Valaxy': RouteRecordInfo<
      '/posts/Tech-Notes/Hello-Valaxy',
      '/posts/Tech-Notes/Hello-Valaxy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Tech-Notes/Introductory-C-Programming-Specialization-Course1': RouteRecordInfo<
      '/posts/Tech-Notes/Introductory-C-Programming-Specialization-Course1',
      '/posts/Tech-Notes/Introductory-C-Programming-Specialization-Course1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Tech-Notes/Introductory-C-Programming-Specialization-Course2': RouteRecordInfo<
      '/posts/Tech-Notes/Introductory-C-Programming-Specialization-Course2',
      '/posts/Tech-Notes/Introductory-C-Programming-Specialization-Course2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/.pnpm/valaxy-theme-yun@0.26.10_vue@3.5.22_typescript@5.9.3_/node_modules/valaxy-theme-yun/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy@0.26.10_@babel+parse_ef4ed80a3fa88367c6b250d29701ecdd/node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'pages/404.md': {
      routes:
        | '/404'
      views:
        | never
    }
    'pages/about/index.md': {
      routes:
        | '/about/'
      views:
        | never
    }
    'pages/about/site.md': {
      routes:
        | '/about/site'
      views:
        | never
    }
    'pages/archives/index.md': {
      routes:
        | '/archives/'
      views:
        | never
    }
    'pages/categories/index.md': {
      routes:
        | '/categories/'
      views:
        | never
    }
    'pages/links/index.md': {
      routes:
        | '/links/'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.26.10_vue@3.5.22_typescript@5.9.3_/node_modules/valaxy-theme-yun/pages/page/[page].vue': {
      routes:
        | '/page/[page]'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.26.10_vue@3.5.22_typescript@5.9.3_/node_modules/valaxy-theme-yun/pages/posts/index.vue': {
      routes:
        | '/posts/'
      views:
        | never
    }
    'pages/posts/Life-Essays/Am-I-into-light-yuri.md': {
      routes:
        | '/posts/Life-Essays/Am-I-into-light-yuri'
      views:
        | never
    }
    'pages/posts/Life-Essays/I-really-love-RADWIMPS——happy-20th-anniversary!.md': {
      routes:
        | '/posts/Life-Essays/I-really-love-RADWIMPS——happy-20th-anniversary!'
      views:
        | never
    }
    'pages/posts/Tech-Notes/Git-Failed-to-connect-to-github.com-port-443.md': {
      routes:
        | '/posts/Tech-Notes/Git-Failed-to-connect-to-github.com-port-443'
      views:
        | never
    }
    'pages/posts/Tech-Notes/Git-Version-Control-Study-Notes.md': {
      routes:
        | '/posts/Tech-Notes/Git-Version-Control-Study-Notes'
      views:
        | never
    }
    'pages/posts/Tech-Notes/githubpages-Quartz-Obsidian-to-bulid-your-Blog.md': {
      routes:
        | '/posts/Tech-Notes/githubpages-Quartz-Obsidian-to-bulid-your-Blog'
      views:
        | never
    }
    'pages/posts/Tech-Notes/Hello-Valaxy.md': {
      routes:
        | '/posts/Tech-Notes/Hello-Valaxy'
      views:
        | never
    }
    'pages/posts/Tech-Notes/Introductory-C-Programming-Specialization-Course1.md': {
      routes:
        | '/posts/Tech-Notes/Introductory-C-Programming-Specialization-Course1'
      views:
        | never
    }
    'pages/posts/Tech-Notes/Introductory-C-Programming-Specialization-Course2.md': {
      routes:
        | '/posts/Tech-Notes/Introductory-C-Programming-Specialization-Course2'
      views:
        | never
    }
    'pages/tags/index.md': {
      routes:
        | '/tags/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
